[tool.poetry]
name = "autocontain"
version = "0.1.0"
description = ""
authors = ["quan-tran-tu <quantrantu2002@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
